

const headerColor = "#043544";

export const styles = {
  container: {
    maxWidth: "320px",
    width: "full",
    margin: "40px auto",
    border: "2px solid #ddd",
    borderRadius: 10,
    overflow: "hidden",
    boxShadow: "0 2px 12px rgba(0,0,0,0.07)",
    display: "flex",
    flexDirection: "column" as const,
    background: "#f5f7fa",
    height: 540,
  },
  header: {
    background: headerColor,
    color: "#ffffff",
    padding: "0 12px",
    fontSize: 18,
    fontWeight: 600,
    letterSpacing: 1,
    borderBottom: "1px solid #173951",
    // textAlign: "center" as const,
    display: "flex",
    alignItems: "center",
    height: 64,
    justifyContent: "space-between" as const,
    justifyItems: "between" as const,
  },
  logoBox: {
    background: "#fff",
    borderRadius: "50%",
    width: 40,
    height: 40,
    display: "flex",
    // alignItems: "center",
    // justifyContent: "center",
    marginRight: 20,
    marginLeft: 0,
  },
  logoImg: {
    width: 38,
    height: 38,
    objectFit: "contain" as const,
    display: "block",
  },
  messages: {
    flex: 1,
    overflowY: "auto" as const,
    padding: "18px 12px",
    display: "flex",
    flexDirection: "column" as const,
    gap: "12px",
    background: "#f5f7fa",
  },
  botBubble: {
    alignSelf: "flex-start" as const,
    backgroundColor: headerColor,
    color: "#ffffff",
    borderRadius: "12px 12px 12px 4px",
    padding: "12px 16px",
    maxWidth: "75%",
    fontSize: 15,
    boxShadow: "0 1px 4px rgba(0,0,0,0.04)",
  },
  userBubble: {
    alignSelf: "flex-end" as const,
    backgroundColor: "#e7b957",
    color: "black",
    borderRadius: "12px 12px 4px 12px",
    padding: "12px 16px",
    maxWidth: "75%",
    fontSize: 15,
    boxShadow: "0 1px 4px rgba(0,0,0,0.04)",
  },
  inputRow: {
    display: "flex",
    flexDirection: "row" as const,
    alignItems: "center",
    padding: "16px 14px",
    borderTop: "1px solid #eee",
    background: "#fff",
    gap: "10px",
  },
  input: {
    flex: 1,
    border: "1px solid #ccc",
    borderRadius: 8,
    padding: "10px 14px",
    fontSize: 15,
    lineHeight: 1.5,
    outline: "none",
    textAlign: "left" as const,
    marginRight: 0,
    background: "#f9f9f9",
    maxHeight: 80,
    overflowY: "auto" as const,
    resize: "none" as const,
    color: "#222",
    minHeight: 40,
    
  },
  button: {
    background: "#043544",
    color: "#fff",
    border: "none",
    borderRadius: 8,
    padding: "10px 18px",
    fontSize: 15,
    fontWeight: 500,
    cursor: "pointer",
    marginLeft: 0,
    transition: "background 0.2s",
    "&:hover": {
      background: "#032f3e",
    },
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
};